<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../ESD.Protocol/ESD.Protocol.csproj"/><PackageReference Include="System.IO.Ports" Version="8.0.0"/></ItemGroup></Project>
