<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><EnableWindowsTargeting>true</EnableWindowsTargeting></PropertyGroup><ItemGroup><ProjectReference Include="../ESD.Protocol/ESD.Protocol.csproj"/><ProjectReference Include="../ESD.Infrastructure/ESD.Infrastructure.csproj"/></ItemGroup></Project>
